require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.6'

target 'fitnessApp' do
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

     # permissions
     permissions_path = '../node_modules/react-native-permissions/ios'
     pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
     pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
     pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
     pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
     pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
     pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"


  target 'fitnessAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

#  post_install do |installer|
#    react_native_post_install(installer)
#    __apply_Xcode_12_5_M1_post_install_workaround(installer)
#  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++14'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.6'
        definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] unless definitions.is_a?(Array)
        if target.name == 'RCT-Folly' && !definitions.include?('FOLLY_HAVE_CLOCK_GETTIME=1')
          definitions << 'FOLLY_HAVE_CLOCK_GETTIME=1'
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions

        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    flipper_transport_types = File.join(__dir__, 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h')
    if File.exist?(flipper_transport_types)
      content = File.read(flipper_transport_types)
      unless content.include?('#include <functional>')
        File.chmod(0o644, flipper_transport_types)
        patched = content.sub("#include <string>", "#include <functional>\n#include <string>")
        File.write(flipper_transport_types, patched)
      end
    end
  end
end
