import { StyleSheet } from 'react-native';
import { ScaledSheet } from 'react-native-size-matters';
import { Colors, Fonts, Metrics } from '../../theme';

export const Styles = ScaledSheet.create({
  header: {
    justifyContent: 'space-between',
    paddingVertical: '32@ms',
  },
  content: {
    flex: 1,
  },
  mapContent: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '90@ms',
  },
  trainerList: {
    flexGrow: 0,
    paddingHorizontal: Metrics.smallMargin,
  },
  trainerItemContainer: {
    height: '216@ms',
    justifyContent: 'flex-end',
    paddingHorizontal: Metrics.smallMargin,
  },
  trainerAvatar: {
    width: '90@ms',
    height: '90@ms',
    borderRadius: '12@ms',
    position: 'absolute',
    zIndex: 1,
    top: 0,
    left: 28,
  },
  trainerItemContent: {
    width: '250@ms',
    height: '181@ms',
    backgroundColor: Colors.tertiary,
    borderRadius: '16@ms',
    paddingVertical: Metrics.baseMargin,
    paddingHorizontal: Metrics.largeMargin,
  },
  like: {
    alignSelf: 'flex-end',
    width: '28@ms',
    alignItems: 'center',
  },
  likesCount: {
    fontSize: '12@ms',
    fontFamily: Fonts.regular,
    marginTop: '2@ms',
  },
  trainerName: {
    fontSize: '14@ms',
    fontFamily: Fonts.medium,
    marginTop: '12@ms',
  },
  timeStyle: {
    fontSize: 23,
    fontFamily: Fonts.medium,
    // marginTop: '5@ms',
  },
  typeStyle: {
    fontSize: '14@ms',
    fontFamily: Fonts.medium,
    marginLeft: '12@ms',
  },
  trainerminiName: {
    fontSize: 10,
    fontFamily: Fonts.medium,
    marginTop: '12@ms',
    textAlign: 'center',
  },
  trainerType: {
    color: Colors.grey2,
    fontSize: '12@ms',
    fontFamily: Fonts.regular,
  },
  trainerActionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: Metrics.baseMargin,
    borderTopColor: Colors.grey3,
    borderTopWidth: 1,
    marginTop: Metrics.baseMargin,
  },
  verticalLine: {
    width: 1,
    height: 26,
    backgroundColor: Colors.grey3,
  },
  fullBox: {
    backgroundColor: Colors.tertiary,
    borderRadius: '14@ms',
    height: '51@ms',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingLeft: Metrics.baseMargin,
    paddingRight: Metrics.smallMargin,
    marginTop: Metrics.smallMargin,
    width: '90%',
  },
  fullBox2: {
    // backgroundColor: Colors.tertiary,
    // borderRadius: '14@ms',
    // height: '51@ms',
    alignItems: 'center',
    // justifyContent: 'space-between',
    flexDirection: 'row',
    // paddingLeft: Metrics.baseMargin,
    // paddingRight: Metrics.smallMargin,
    marginTop: Metrics.smallMargin,
    // width: '90%',
  },
  timeFull: {
    fontFamily: Fonts.regular,
    fontSize: '13@ms',
  },
  loactionHeading: {
    fontFamily: Fonts.regular,
    fontSize: '10@ms',
  },
  priceText: {
    fontFamily: Fonts.regular,
    fontSize: '20@ms',
  },
  otherText: {
    fontFamily: Fonts.regular,
    fontSize: '12@ms',
    color: Colors.lightGrey,
    // marginBottom: '12@ms',
  },
  descText: {
    fontFamily: Fonts.regular,
    fontSize: '12@ms',
    color: Colors.lightGrey,
    marginBottom: '12@ms',
  },
  orContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: Metrics.smallMargin,
    paddingHorizontal: Metrics.baseMargin,
  },
  horizontalLine: {
    width: '100%',
    height: 0.5,
    backgroundColor: Colors.grey1,
  },
  tagView: {
    alignSelf: 'flex-start',
    marginVertical: Metrics.miniMargin,
    padding: '6@ms',
    borderRadius: 8,
    backgroundColor: Colors.blue,
  },
  tagViewText: {
    color: Colors.white,
    fontSize: '11@ms',
  },
  countdigitStyle: {
    height: 28,
    width: 26,
  },
  countdigitTxtStyle: {
    color: Colors.white,
    fontSize: Fonts.size.size_20,
  },
  bottomSheetWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  bottomSheet: {
    backgroundColor: Colors.secondary,
    borderTopLeftRadius: '16@ms',
    borderTopRightRadius: '16@ms',
    borderWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 0,
    borderColor: Colors.greyborder,
    paddingBottom: '10@ms',
    zIndex: 20,
    elevation: 12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  sheetDragZone: {
    width: '100%',
  },
  sheetDragInner: {
    alignItems: 'center',
    paddingHorizontal: Metrics.baseMargin,
    paddingBottom: '4@ms',
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetFlatList: {
    flex: 1,
  },
  sheetLoadingWrap: {
    alignItems: 'center',
    paddingVertical: '24@ms',
    paddingHorizontal: Metrics.baseMargin,
  },
  sheetLoadingCaption: {
    marginTop: '10@ms',
    textAlign: 'center',
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    width: '40@ms',
    height: '4@ms',
    borderRadius: '2@ms',
    backgroundColor: Colors.grey3,
    marginTop: '8@ms',
    marginBottom: '10@ms',
  },
  bottomSheetTitle: {
    fontFamily: Fonts.semiBold,
    fontSize: '16@ms',
    color: Colors.white,
    marginBottom: '4@ms',
    textAlign: 'center',
  },
  bottomSheetEmpty: {
    fontFamily: Fonts.regular,
    fontSize: '13@ms',
    color: Colors.grey2,
    paddingHorizontal: Metrics.baseMargin,
    paddingBottom: '20@ms',
  },
  bottomSheetList: {
    paddingHorizontal: Metrics.smallMargin,
    paddingBottom: '8@ms',
  },
  sheetRow: {
    flexDirection: 'row',
    paddingVertical: '12@ms',
    paddingHorizontal: Metrics.smallMargin,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.grey3,
  },
  sheetRowAvatar: {
    width: '56@ms',
    height: '56@ms',
    borderRadius: '10@ms',
  },
  sheetRowBody: {
    flex: 1,
    marginLeft: '12@ms',
  },
  sheetRowName: {
    fontFamily: Fonts.semiBold,
    fontSize: '14@ms',
    color: Colors.white,
  },
  sheetRowMeta: {
    fontFamily: Fonts.regular,
    fontSize: '11@ms',
    color: Colors.grey2,
    marginTop: '4@ms',
  },
  sheetRowBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: '4@ms',
  },
  sheetOnline: {
    fontFamily: Fonts.medium,
    fontSize: '10@ms',
    color: Colors.lightGreen,
    marginRight: '8@ms',
  },
  sheetRowAddress: {
    fontFamily: Fonts.regular,
    fontSize: '11@ms',
    color: Colors.lightGrey,
    marginTop: '6@ms',
  },
  sheetRowPrice: {
    fontFamily: Fonts.medium,
    fontSize: '13@ms',
    color: Colors.primary,
    marginTop: '6@ms',
  },
  sheetMapSelectionClear: {
    alignSelf: 'flex-end',
    paddingHorizontal: Metrics.smallMargin,
    paddingVertical: '6@ms',
  },
  sheetMapSelectionClearText: {
    fontFamily: Fonts.medium,
    fontSize: '12@ms',
    color: Colors.grey2,
  },
});
